---
title: "Simple document"
output: html_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```



This document will show how to import data.


## Import the FAS Litters CSV

```{r}
litters_df = read_csv("data/FAS_litters.csv")

litters_df = janitor::clean_names(litters_df)
```


### Look at the dataset

```{r}
litters_df

head(litters_df)
tail(litters_df)
```

```{r eval = FALSE}
view(litters_df)
```


## Import dataset FAS_pups

Use relative path

```{r, eval = FALSE}
pups_df = read_csv("data/FAS_pups.csv")

pups_df = janitor::clean_names(pups_df)

pups_df
```

Use absolute path

```{r, eval = FALSE}
pups_df = read_csv("/Users/wenjiewu/Desktop/Columbia/Data Science/20120917/data_wrangling_1/data/FAS_pups.csv")

pups_df
```

## Look at read_csv options

col_names and skipping rows

```{r}
litters_df = 
  read_csv(
    file = "data/FAS_litters.csv",
    skip = 2
  )
```

What about missing data

```{r}
litters_df = 
  read_csv(
    file = "data/FAS_litters.csv",
    na = c("NA", ",", ".")
  )
```

What if we code 'group' as a factor variable?

```{r}
litters_df = 
  read_csv(
    file = "data/FAS_litters.csv",
    na = c("NA", ",", "."),
    col_types = cols(
      Group = col_factor()
    )
  )
```

## Import excel file

Import MLB

```{r}
mlb_df = read_excel("data/mlb_11.xlsx", sheet = "mlb11")
```


## Import SAS data

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```